### ISSUE TITLE
Setting to input unicode-latex directly in editor

### ISSUE THREAD

**Issue by cossio** [ojsheikh/unicode-latex#2]
I am thinking of the behavior of the atom latex completions extension:

https://github.com/JunoLab/atom-latex-completions

For me having to open the command, enter "Insert Unicode ...", and finally typing '\alpha', is a hassle. It would be nice if (perhaps by doing some config), `\alpha` be replaced directly with the unicode character, maybe by pressing TAB.

Could this be supported with this extension?

**Comment by ojsheikh** [comment]
Sorry for not looking into this for such a long time.

Doing it the way atom extension does it should be possible by providing the completions as snippets, or possibly by registering a `CompletionItemProvider`.

**Comment by ojsheikh** [comment]
Added autocompletion last week. It is currently only for plain text files as I rather not pollute the list of completions, especially for languages where '\' is used extensively. Feel free to open an issue if that is insufficient for your use-case(s).

The implementation uses a CompletionItemProvider instead of snippets because snippets seem to require whitespace between symbols.

**Comment by varkor** [comment]
Is there any way to enable support for other languages, for instance Coq (`.v` files)?

**Comment by jotaf98** [comment]
I'd also like to enable auto-complete in another language. Could this be user-configurable? (E.g. choose a list of file extensions or languages in settings)
